### ISSUE TITLE
Codeforces AC/WA not visible on the problemsets page

### ISSUE THREAD

**Issue by MaximDC** [Technici4n/BeOI-Training#9]
Initials: MDC
Codeforces handle: maximdc
Problems:
    722C - Destroying Array: TLE
    701A - Cards: AC
    757B - Bash's Big Day: AC
    743B - Chloe and the sequence: AC
    616C - The Labyrinth: AC

**Comment by RobinJadoul** [comment]
![image](https://user-images.githubusercontent.com/16085366/35937725-6f0a8d3e-0c47-11e8-9949-e8c5fda43f5e.png)
Please load the page over http instead of https (as indicated by the warning at the top of the page when viewing over https), and wait a little while for the data to update. Codeforces is rather strictly rate limiting everyone...

**Comment by AstroGeeks** [comment]
I have never loaded the site over https, so I think that's not the problem.

**Comment by MaximDC** [comment]
I have never loaded the site over https, so that's not the problem.

**Comment by RobinJadoul** [comment]
As you can see in my screenshot, it works for me.
Can you try to keep the problemsets page open for a long enough period? We can only fetch the results for a few users every couple of minutes, so it may take a while before you get scheduled for an update.

**Comment by Technici4n** [comment]
Or just keep any page of the website open, it works too.
And thanks for filing an issue!
